version: "3"

volumes:
  drone:
    driver: local

services:
  drone-server:
    image: drone/drone:2
    container_name: drone-server
    environment:
      - DRONE_GITEA_SERVER=https://services.infra.home:4443
      - DRONE_GITEA_CLIENT_ID=$DRONE_GITEA_CLIENT_ID
      - DRONE_GITEA_CLIENT_SECRET=$DRONE_GITEA_CLIENT_SECRET
      - DRONE_RPC_SECRET=$DRONE_RPC_SECRET
      - DRONE_SERVER_HOST=services.infra.home:6443
      - DRONE_SERVER_PROTO=https
      - DRONE_TLS_CERT=/etc/certs/services.infra.home.crt
      - DRONE_TLS_KEY=/etc/certs/services.infra.home.key
      - DRONE_GITEA_SKIP_VERIFY=true
    ports:
      - "6080:80"
      - "6443:443"
    restart: always
    volumes:
      - /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt:ro
      - $CERTS_PATH:/etc/certs
  
  drone-runner-docker:
    image: drone/drone-runner-docker:1
    container_name: drone-runner-docker
    environment:
      - DRONE_RPC_PROTO=https
      - DRONE_RPC_HOST=services.infra.home:6443
      - DRONE_RPC_SECRET=$DRONE_RPC_SECRET
      - DRONE_RUNNER_CAPACITY=2
      - DRONE_RUNNER_NAME=services-runner
      - DRONE_RUNNER_VOLUMES=/etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt
    ports:
      - "6500:3000"
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt:ro
    depends_on:
      - drone-server